name       : python-jupyter_core
version    : 4.4.0
release    : 2
source     :
    - https://github.com/jupyter/jupyter_core/archive/4.4.0.tar.gz : a3c693cb4cd1251f887f034eba4b74e5ad1beab5baef43cc3ae9387450e72367
license    : BSD-3-Clause
component  : programming.python
summary    : Core Jupyter functionality.
description: |
    Core Jupyter functionality.
builddeps  :
    - pkgconfig(python-3.5)
    - python-setuptools
rundeps    :
    - python-traitlets
setup      : |
    %python3_setup
    %python_setup
install    : |
    %python3_install
    for _f in "$installdir"/usr/bin/*; do
        mv -v "$_f" "${_f}3"
    done
    %python_install
