name       : python-jupyter_core
version    : 4.7.1
release    : 7
source     :
    - https://github.com/jupyter/jupyter_core/archive/4.7.1.tar.gz : dfdd5af7aceb79b41b4a57fef580f56d4ad5102bffdc723cb4f442926f0dc48f
homepage   : https://github.com/jupyter/jupyter_core
license    : BSD-3-Clause
component  : programming.python
summary    : Core Jupyter functionality
description: |
    Core Jupyter functionality.
builddeps  :
    - pkgconfig(python3)
    - python-ipykernel  # check
    - python-nose       # check
    - python-pytest     # check
    - python-traitlets  # check
rundeps    :
    - python-traitlets
setup      : |
    %python3_setup
install    : |
    %python3_install
    install -Dm00644 examples/jupyter-completion.bash $installdir/usr/share/bash-completion/completions/jupyter
    install -Dm00644 examples/completions-zsh $installdir/usr/share/zsh/site-functions/_jupyter
check      : |
    # Filed test reported upstream https://github.com/jupyter/jupyter_core/issues/208
    %python3_test py.test3 -v -k 'not test_jupyter_path_prefer_env'
