name       : python-jupyter_core
version    : 4.3.0
release    : 1
source     :
    - https://github.com/jupyter/jupyter_core/archive/4.3.0.tar.gz : 9fdca98cc6d2f2c7faac8be53d35d5cbb4891fe3822aa678b7e84a2514d135bb
license    : BSD-3-Clause
component  : programming.python
summary    : Core Jupyter functionality.
description: |
    Core Jupyter functionality.
builddeps  :
    - pkgconfig(python-3.5)
    - python-setuptools
rundeps    :
    - python-traitlets
setup      : |
    %python3_setup
    %python_setup
install    : |
    %python3_install
    for _f in "$installdir"/usr/bin/*; do
        mv -v "$_f" "${_f}3"
    done
    %python_install
