name       : python-jupyter_core
version    : 4.9.2
release    : 9
source     :
    - https://files.pythonhosted.org/packages/source/j/jupyter_core/jupyter_core-4.9.2.tar.gz : d69baeb9ffb128b8cd2657fcf2703f89c769d1673c851812119e3a2a0e93ad9a
homepage   : https://github.com/jupyter/jupyter_core
license    : BSD-3-Clause
component  : programming.python
summary    : Core Jupyter functionality
description: |
    Jupyter core package. A base package on which Jupyter projects rely.
builddeps  :
    - python-ipykernel  # check
    - python-nose       # check
    - python-pytest     # check
    - python-traitlets  # check
rundeps    :
    - python-traitlets
setup      : |
    %python3_setup
install    : |
    %python3_install
    install -Dm00644 examples/jupyter-completion.bash $installdir/usr/share/bash-completion/completions/jupyter
    install -Dm00644 examples/completions-zsh $installdir/usr/share/zsh/site-functions/_jupyter
#check      : |
    # Failed test reported upstream https://github.com/jupyter/jupyter_core/issues/231
    #python3_test pytest3 -v \
    #    --deselect jupyter_core/tests/test_paths.py::test_jupyter_path_user_site \
    #    --deselect jupyter_core/tests/test_paths.py::test_jupyter_path_no_user_site \
    #    --deselect jupyter_core/tests/test_paths.py::test_jupyter_path_prefer_env
